Repository Codenits/UnoMemo, pull requests merged in 2021-10, with the labels that each got.

#4 last opp bilder fragment , layout, lat opp bilder fragment , layout, dropdown - adapter for det - adapter
  .idea/misc.xml
  app/src/main/java/com/example/unomemo/LastOppBilde/LastoppBilde.kt
  app/src/main/java/com/example/unomemo/LastOppBilde/VelgBildeAdapter.kt
  app/src/main/java/com/example/unomemo/spillKort/SpillBrettAdatper.kt
  app/src/main/java/com/example/unomemo/spillKort/SpillKort.kt
  app/src/main/res/drawable/ic_baseline_image_24.xml
  app/src/main/res/drawable/ic_baseline_refresh_24.xml
  app/src/main/res/layout/bilde_kort_layout.xml
  app/src/main/res/layout/dropdown_item.xml
  app/src/main/res/layout/fragment_lastopp_bilde_fragement.xml
  app/src/main/res/layout/fragment_spill_kort.xml
  app/src/main/res/layout/spillkortlayout.xml
  app/src/main/res/menu/option_menu.xml
  app/src/main/res/navigation/navagtion.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: newcode

#5 login fix, extended fab,nav meny opdatering
  .idea/misc.xml
  app/src/main/java/com/example/unomemo/login/LoginFragment.kt
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/menu/navdrawer_menu.xml
  app/src/main/res/values/strings.xml
Labels: newcode

#9 Leaderboard og dummy data
  .idea/misc.xml
  app/src/main/java/com/example/unomemo/KatgoryFragment.kt
  app/src/main/java/com/example/unomemo/LeaderboardFragment.kt
  app/src/main/java/com/example/unomemo/MainActivity.kt
  app/src/main/java/com/example/unomemo/kategori/KategoriData.kt
  app/src/main/java/com/example/unomemo/kategori/KategoriListeAdapter.kt
  app/src/main/java/com/example/unomemo/leaderboard/LeaderboardAdapter.kt
  app/src/main/res/font/roboto.xml
  app/src/main/res/layout/fragment_katgory.xml
  app/src/main/res/layout/fragment_leaderboard.xml
  app/src/main/res/layout/kategori_list_item.xml
  app/src/main/res/layout/spiller_item.xml
  app/src/main/res/menu/navdrawer_menu.xml
  app/src/main/res/navigation/navagtion.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, newcode

#16 fixForeverRecursiveCall
  .gitignore
  .idea/.gitignore
  .idea/misc.xml
  app/build.gradle
  app/src/main/java/com/example/unomemo/AboutFragment.kt
  app/src/main/java/com/example/unomemo/AccountFragment.kt
  app/src/main/java/com/example/unomemo/EntryPointFragment.kt
  app/src/main/java/com/example/unomemo/KatgoryFragment.kt
  app/src/main/java/com/example/unomemo/MainActivity.kt
  app/src/main/java/com/example/unomemo/RulesFragment.kt
  app/src/main/java/com/example/unomemo/SettingsFragment.kt
  app/src/main/java/com/example/unomemo/kategori/KategoriData.kt
  app/src/main/java/com/example/unomemo/login/LoginFragment.kt
  app/src/main/java/com/example/unomemo/spillData/Vanskelighetsgrad.kt
  app/src/main/res/layout-w1240dp/fragment_login.xml
  app/src/main/res/layout-w936dp/fragment_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/dropdown_item.xml
  app/src/main/res/layout/fragment_about.xml
  app/src/main/res/layout/fragment_account.xml
  app/src/main/res/layout/fragment_lastopp_bilde_fragement.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_rules.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/menu/navdrawer_menu.xml
  app/src/main/res/navigation/navagtion.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: bug

#18 Firebase Configuration
  .idea/misc.xml
  app/build.gradle
  app/google-services.json
  build.gradle
Labels: enhancement

#19 gradle-opdatering
  .gitignore
  app/build.gradle
  app/src/main/java/com/example/unomemo/lastoppbilde/VelgBildeAdapter.kt
  app/src/main/java/com/example/unomemo/spillKort/DefualtDecorator.kt
  app/src/main/java/com/example/unomemo/spillKort/SpillBrettAdatper.kt
  app/src/main/java/com/example/unomemo/spillKort/SpillKort.kt
  app/src/main/java/com/example/unomemo/spilldata/Const.kt
  app/src/main/java/com/example/unomemo/spilldata/KortInfo.kt
  app/src/main/java/com/example/unomemo/spilldata/Vanskelighetsgrad.kt
  build.gradle
Labels: fix, dependency_update
